spring.application.name=FlightCheckInApplication
spring.datasource.url=jdbc:mysql://terraform-20260401042652634800000002.cns8uqs6i9bo.ap-southeast-2.rds.amazonaws.com:3306/checkin_db?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=Redhat123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
booking.service.url=http://34.238.151.237:8080/api/bookings
server.port=8081
frontend.url=http://3.93.154.213:80
